import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "./components/navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[
          "antialiased",
          "font-(family-name:--font-psk)",
          "flex",
          "justify-center",
        ].join(" ")}
      >
        <main
          className={[
            "min-h-screen",
            "w-full",
            "max-w-5xl",
            "bg-white",
            "dark:bg-black",
          ].join(" ")}
        >
          <Navigation />
          {children}
        </main>
      </body>
    </html>
  );
}
