import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { twMerge } from "tailwind-merge";
import { IBM_Plex_Sans_Thai } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plex_sans = IBM_Plex_Sans_Thai({
  weight: ["400", "700"],
  subsets: ["thai"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twMerge([
          "antialiased",
          "flex",
          "justify-center",
          "bg-gray-200",
          plex_sans.className,
        ])}
      >
        <Navigation />
        <main
          id="main"
          className={twMerge(["w-full", "max-w-7xl", "shadow-xl"])}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
