import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const plex_sans = IBM_Plex_Sans_Thai({
  weight: ["400", "700"],
  subsets: ["thai"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("")}>
      <body className={cn("antialiased", plex_sans.className)}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
